
angular.module('monitor.process.diagram')
  .factory('svgActivityImgRoute', ['$rootScope','$location',function ($rootScope,$location) {
    var path = "images/svg/"; // "/tea/sr/BusinessWorks/6.3.0/app/svg/"
    var imageMap = {

      bw: {
        http:{
          sendHTTPRequest:{
            value:path+"resource/images/sendHTTPRequestActivity.png_48x48.png"
          },
          HTTPReceiver:{
            value:path+"resource/images/httpReceiverStarter_48x48.png"
          },
          sendHTTPResponse:{
            value:path+"resource/images/sendHTTPResponseActivity_48x48.png"
          },
          waitForHTTPRequest:{
            value:path+"resource/images/waitForHTTPRequestSignal_48x48.png"
          }
        },
        jms:{
          getmsg:{
            value:path+"resource/images/getJMSQueueMessageActivity_48x48.png"
          },
          receive:{
            value:path+"resource/images/jmsReceiveMessageStarter_48x48.png"
          },
          requestreply:{
            value:path+"resource/images/jmsRequestReplyActivity_48x48.png"
          },
          send:{
            value:path+"resource/images/jmsSendActivity_48x48.png"
          },
          reply:{
            value:path+"resource/images/replyToJMSMessageActivity_48x48.png"
          },
          signalin:{
            value:path+"resource/images/waitForJMSMessageSignal_48x48.png"
          }
        },
        mail:{
          receive:{
            value:path+"resource/images/receiveMailStarter_48x48.png"
          },
          send:{
            value:path+"resource/images/sendMailActivity_48x48.png"
          }
        },
        rv:{
          publishRVMessage:{
            value:path+"resource/images/publishRendezvousMessageActivity_48x48.png"
          },
          replytoRVRequest:{
            value:path+"resource/images/replyToRendezvousRequestActivity_48x48.png"
          },
          sendRVRequest:{
            value:path+"resource/images/sendRendezvousRequestActivity_48x48.png"
          },
          rvSubscriber:{
            value:path+"resource/images/rendezvousSubscriberStarter_48x48.png"
          },
          waitforRVMessage:{
            value:path+"resource/images/waitForRendezvousMessageSignal_48x48.png"
          }
        },
        parse:{
          mimeparser:{
            value:path+"resource/images/mimeParserActivity.gif"
          },
          parsedata:{
            value:path+"resource/images/parseDataActivity_48x48.png"
          },
          renderdata:{
            value:path+"resource/images/renderDataActivity_48x48.png"
          }
        },
        rest:{
          value:path+"resource/images/rest_binding3_16x16.png"
        },
        soap:{
          value:path+"resource/images/soap_provider_def.png"
        },
        generalactivities: {
          timer:{
            value:path+"resource/images/timer.png"
          },
          log:{
            value:path+"resource/images/log.png"
          },
          sleep:{
            value:path+"resource/images/sleep.png"
          },
          bwassign:{
            value:path+"resource/images/assignActivity_48x48.png"
          },
          mapper:{
            value:path+"resource/images/mapperActivity_48x48.png"
          },
          confirm:{
            value:path+"resource/images/confirmActivity_48x48.png"
          },
          externalcommand:{
            value:path+"resource/images/externalCommandActivity_48x48.png"
          }
        },
        file:{
          read:{
            value:path+"resource/images/readFileActivity_48x48.png"
          },
          write:{
            value:path+"resource/images/writeFile.png"
          },
          remove:{
            value:path+"resource/images/removeFileActivity_48x48.png"
          },

          copy:{
            value:path+"resource/images/copyFileActivity_48x48.png"
          },
          create:{
            value:path+"resource/images/createFileActivity_48x48.png"
          },
          poller:{
            value:path+"resource/images/filePollerStarter_48x48.png"
          },
          list:{
            value:path+"resource/images/listFilesActivity_48x48.png"
          },
          rename:{
            value:path+"resource/images/renameFileActivity_48x48.png"
          },
          wait:{
            value:path+"resource/images/waitForFileChangeSignal_48x48.png"
          }
        },
        ftp:{
          changeDefaultDir:{
            value:path+"resource/images/ftpChangeDefaultDirectoryActivity_48x48.png"
          },
          removeFile:{
            value:path+"resource/images/ftpDeleteFileActivity_48x48.png"
          },
          dir:{
            value:path+"resource/images/ftpDirActivity_48x48.png"
          },
          get:{
            value:path+"resource/images/ftpGetActivity_48x48.png"
          },
          getDefaultDir:{
            value:path+"resource/images/ftpGetDefaultDirectoryActivity_48x48.png"
          },
          makeDir:{
            value:path+"resource/images/ftpMakeRemoteDirectoryActivity_48x48.png"
          },
          put:{
            value:path+"resource/images/ftpPutActivity_48x48.png"
          },
          quote:{
            value:path+"resource/images/quote.gif"
          },
          removeDir:{
            value:path+"resource/images/ftpRemoveRemoteDirectoryActivity_48x48.png"
          },
          renameFile:{
            value:path+"resource/images/ftpRenameFileActivity_48x48.png"
          },
          sysType:{
            value:path+"resource/images/ftpSysTypeActivity_48x48.png"
          }
        },
        internal:{
          getContext:{
            value:path+"resource/images/get_context_activity_48x48.png"
          },
          setContext:{
            value:path+"resource/images/set_context_activity_48x48.png"
          },
          setEPR:{
            value:path+"resource/images/set_epr_activity_48x48.png"
          },
          checkpoint:{
            value:path+"resource/images/checkPointActivity_48x48.png"
          },
          getSharedVariable:{
            value:path+"resource/images/getSharedVariableActivity_48x48.png"
          },
          inspector:{
            value:path+"resource/images/inspectorActivity_48x48.png"
          },
          setSharedVariable:{
            value:path+"resource/images/setSharedVariableActivity_48x48.png"
          }
        },
        xml:{
          parsexml:{
            value:path+"resource/images/parseXmlActivity_48x48.png"
          },
          renderxml:{
            value:path+"resource/images/renderXmlActivity_48x48.png"
          },
          transformxml:{
            value:path+"resource/images/transformXmlActivity_48x48.png"
          }
        },
        jdbc:{
          JDBCQuery:{
            value:path+"resource/images/jdbcQueryActivity_48x48.png",
          },
          update:{
            value:path+"resource/images/jdbcUpdateActivity_48x48.png"
          },
          JDBCCallProcedure:{
            value:path+"resource/images/jdbcCallProcedureActivity_48x48.png",
          },
          SQLDirect:{
            value:path+"resource/images/jdbcPalette_48x48.png"
          }
        },
        tcp:{
          read:{
            value:path+"resource/images/readTCPDataActivity_48x48.png",
          },
          tcpcloseconnection:{
            value:path+"resource/images/tcpCloseConnectionActivity_48x48.png",
          },
          tcpopenconnection:{
            value:path+"resource/images/tcpOpenConnectionActivity_48x48.png",
          },
          receive:{
            value:path+"resource/images/tcpReceiverStarter_48x48.png",
          },
          waitfortcp:{
            value:path+"resource/images/waitForTCPRequestSignal_48x48.png",
          },
          write:{
            value:path+"resource/images/writeTCPDataActivity_48x48.png",
          }
        },
        java:{
          javamethod:{
            value:path+"resource/images/javaMethodActivity_48x48.png",
          },
          javaeventsource:{
            value:path+"resource/images/javaEventSourceStarter_48x48.png",
          },
          javatoxml:{
            value:path+"resource/images/javaToXmlActivity_48x48.png",
          },
          xmltojava:{
            value:path+"resource/images/xmlToJavaActivity_48x48.png",
          }
        },
        ftl:{
          publisher:{
            value:path+"resource/images/FTLPublisher_48x48.png",
          },
          reply:{
            value:path+"resource/images/FTLReply_48x48.png",
          },
          requestreply:{
            value:path+"resource/images/FTLRequestReply_48x48.png",
          },
          subscriber:{
            value:path+"resource/images/FTLSubscriber_48x48.png",
          }
        },
        restjson:{
          Rest:{
            value:path+"resource/images/sendHTTPRequestActivity.png_48x48.png"
          },
          JsonParser:{
            value:path+"resource/images/parseJSON_48x48.png"
          },
          JsonRender:{
            value:path+"resource/images/renderJSON_48x48.png"
          }
        }
      },
      groupStart:{
        value:path+"resource/images/groupStart.png"
      },
      group:{
        value:path+"resource/images/group.png"
      },
      catchLeftImg:{
        value:path+"resource/images/catch32.gif"
      },
      onEvent:{
        value:path+"resource/images/MEP_out_in_16x16.png"
      },
      onMesageIn:{
        value:path+"resource/images/MEP_in_only_16x16.png"
      },
      onMesageOut:{
        value:path+"resource/images/MEP_out_only_16x16.png"
      },
      constructorOperation:{
        value:path+"resource/images/current_decorator.gif"
      },
      eventHandlersLeftImg:{
        value:path+"resource/images/onEvent32.gif"
      },
      catch:{
        value:path+"resource/images/catch_16x16.png"
      },
      groupEnd:{
        value:path+"resource/images/groupEnd.png"
      },
      onMessageStart:{
        value:path+"resource/images/groupStart.png"
      },
      onMessageEnd:{
        value:path+"resource/images/groupEnd.png"
      },
      collapse:{
        value:path+"resource/images/collapse.png"
      },
      uncollapse:{
        value:path+"resource/images/uncollapse.png"
      },
      unpin:{
        value:path+"resource/images/unpin.gif"
      },
      menu:{
        value:path+"resource/images/menu_16x16.png"
      },
      compensation:{
        handler:{
          value:path+"resource/images/compensation_handler_16x16.png"
        }
      },
      com:{
        tibco:{
          bw:{
            core:{
              design:{
                process:{
                  editor:{
                    Activity_4002_Empty:{
                      value:path+"resource/images/empty.png"
                    },
                    Activity_4002_Reply:{
                      value:path+"resource/images/replyActivity_48x48.png"
                    },
                    Activity_4002_Invoke:{
                      value:path+"resource/images/invokeProcessActivity_48x48.png"
                    },
                    Activity_4002_Receive:{
                      value:path+"resource/images/receiveStarter_48x48.png"
                    },
                    Activity_4002_Receive_1:{
                      value:path+"resource/images/receiveSignal_48x48.png"
                    },
                    Activity_4002_Rethrow:{
                      value:path+"resource/images/rethrowActivity_48x48.png"
                    }
                  }
                }
              }
            }
          }
        }
      },
      catchAllLeftImg:{
        value:path+"resource/images/catchAll32.gif"
      },
      catchAll:{
        value:path+"resource/images/catch_all_16x16.png"
      },
      pick:{
        value:path+"resource/images/pick.gif"
      },
      parenerLeft:{
        value:path+"resource/images/ServicePartnerLink_45x32.gif"
      },
      parenerRight:{
        value:path+"resource/images/ReferencePartnerLinkPrivate_45x32.gif"
      },
      referenceImgPath:{
        value:path+"resource/images/reference_16x16.png"
      },
      serversImgPath:{
        value:path+"resource/images/service_16x16.png"
      },
      interfaceImgPath:{
        value:path+"resource/images/porttype_obj.gif"
      },
      restServerImgPath : {
        value:path+"resource/images/restResource_16x16.png"
      }
    }
    imageMap.getPath = function(path){
      return imageMap.get(path,"value");
    }
    imageMap.getConfig = function(path){
      return imageMap.get(path,"config");
    }
    imageMap.get = function(path,type){
      var value = "";
      if(path){
        var pathArray = path.split(".");
        if(pathArray.length > 1){
          var current_obj = null;
          for(var i = 0; i < pathArray.length; i++){
            if(current_obj == null){
              current_obj = imageMap[pathArray[i]];
            }else{
              current_obj = current_obj[pathArray[i]];
            }
          }
          if(current_obj){
            value = current_obj[type];
          }
        }else{
          value = imageMap[path][type];
        }
        return value;
      }
    }
    var exports = {
      imageMap:imageMap
    }
    return exports;
  }])